import { google } from 'googleapis';
import fs from 'fs';
import path from 'path';

export class GoogleCalendarService {
  private oauth2Client;
  private calendar;

  constructor() {
    this.oauth2Client = new google.auth.OAuth2(
      process.env.GOOGLE_CLIENT_ID,
      process.env.GOOGLE_CLIENT_SECRET,
      'http://localhost:3000/api/auth/callback/google'
    );

    const tokenPath = path.join(process.cwd(), '.google-token.json');
    if (fs.existsSync(tokenPath)) {
      const tokens = JSON.parse(fs.readFileSync(tokenPath, 'utf8'));
      this.oauth2Client.setCredentials(tokens);
    }

    this.calendar = google.calendar({ version: 'v3', auth: this.oauth2Client });
  }

  // Gets or creates a dedicated EXECOS Demo Calendar
  private async getDemoCalendarId(): Promise<string> {
    const calendarName = 'EXECOS Demo Calendar';
    const { data } = await this.calendar.calendarList.list();
    const existing = data.items?.find(c => c.summary === calendarName);
    
    if (existing && existing.id) return existing.id;

    // Create it if it doesn't exist
    const newCal = await this.calendar.calendars.insert({
      requestBody: {
        summary: calendarName,
        description: 'Autogenerated by EXECOS Agentic OS'
      }
    });
    
    return newCal.data.id || 'primary';
  }

  public async insertEvent(title: string, startTime: Date, durationMins: number) {
    try {
      const calendarId = await this.getDemoCalendarId();
      
      const endTime = new Date(startTime.getTime() + durationMins * 60000);

      const event = {
        summary: `[EXECOS] ${title}`,
        colorId: '9', // Blueberry color
        start: {
          dateTime: startTime.toISOString(),
          timeZone: 'UTC',
        },
        end: {
          dateTime: endTime.toISOString(),
          timeZone: 'UTC',
        },
      };

      const res = await this.calendar.events.insert({
        calendarId,
        requestBody: event,
      });

      return res.data;
    } catch (error) {
      console.error('[GoogleCalendarService] Failed to insert event:', error);
      throw error;
    }
  }
}
